CREATE OR REPLACE DATABASE CORTEX_POC;

CREATE OR REPLACE SCHEMA LLM_FUNC;

create or replace WAREHOUSE CORTEX_WH WITH WAREHOUSE_SIZE = 'XSMALL' 
WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 600 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 2 SCALING_POLICY = 'STANDARD';

USE ROLE SYSADMIN;
USE DATABASE CORTEX_POC;
USE SCHEMA LLM_FUNC;
USE WAREHOUSE CORTEX_WH;


SELECT
  *
FROM
  CORTEX_POC.LLM_FUNC.SUPERSTORE_SALES;

describe table superstore_sales;

CREATE OR REPLACE CORTEX SEARCH SERVICE SUPERSTORE_SS
ON SEARCH_COL
ATTRIBUTES SEGMENT
WAREHOUSE = CORTEX_WH
TARGET_LAG = '1 minute'
AS(
SELECT CONCAT('SUB_CATEGORY: ',SUB_CATEGORY, '\nPRODUCT_NAME: ', PRODUCT_NAME) as SEARCH_COL,
ORDER_ID,
ORDER_DATE,
SHIP_DATE,
SHIP_MODE,
CUSTOMER_ID,
CUSTOMER_NAME,
SEGMENT,
COUNTRY,
CITY,
STATE,
POSTAL_CODE,
REGION,
PRODUCT_ID,
CATEGORY,
SUB_CATEGORY,
PRODUCT_NAME,
SALES,
QUANTITY,
DISCOUNT,
PROFIT
FROM SUPERSTORE_SALES
);

SELECT DISTINCT SEGMENT FROM SUPERSTORE_SALES;
SELECT DISTINCT CATEGORY FROM SUPERSTORE_SALES;
SELECT DISTINCT SUB_CATEGORY FROM SUPERSTORE_SALES;
SELECT * FROM SUPERSTORE_SALES WHERE SEGMENT='Corporate';
SELECT COUNT(*) FROM SUPERSTORE_SALES;

SELECT 
    TO_CHAR(ORDER_DATE, 'YYYY-MM') AS MONTH,
    STATE,
    SUM(SALES) AS TOTAL_SALES
FROM 
    SUPERSTORE_SALES
GROUP BY 
    MONTH,
    STATE
ORDER BY 
    MONTH, 
    STATE;

    SELECT 
    SHIP_MODE,
    CUSTOMER_ID,
    SUM(QUANTITY) AS TOTAL_QUANTITY
FROM 
    SUPERSTORE_SALES
GROUP BY 
    SHIP_MODE, 
    CUSTOMER_ID
ORDER BY 
    SHIP_MODE, 
    TOTAL_QUANTITY DESC;

    SELECT 
    REGION,
    CATEGORY,
    SUM(SALES) AS TOTAL_SALES,
    AVG(DISCOUNT) AS AVG_DISCOUNT
FROM 
    SUPERSTORE_SALES
WHERE 
    DISCOUNT > 0  -- Only consider entries with discounts
GROUP BY 
    REGION, 
    CATEGORY
ORDER BY 
    REGION, 
    CATEGORY;

SELECT 
    SUB_CATEGORY,
    DISCOUNT,
    SUM(SALES) AS TOTAL_SALES
FROM 
    SUPERSTORE_SALES
GROUP BY 
    SUB_CATEGORY, 
    DISCOUNT
ORDER BY 
    SUB_CATEGORY, 
    DISCOUNT;