CREATE OR REPLACE DATABASE CORTEX_POC;

CREATE OR REPLACE SCHEMA SUMMIT;

create or replace WAREHOUSE CORTEX_WH WITH WAREHOUSE_SIZE = 'XSMALL' 
WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 600 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 2 SCALING_POLICY = 'STANDARD';

USE ROLE SYSADMIN;
USE DATABASE CORTEX_POC;
USE SCHEMA SUMMIT;

USE WAREHOUSE CORTEX_WH;

SELECT * FROM TED_MAIN LIMIT 10;

SELECT CONCAT('DESCRIPTION: ', DESCRIPTION, '\nNAME: ', NAME) FROM TED_MAIN LIMIT 10;

CREATE OR REPLACE CORTEX SEARCH SERVICE TED_SS
ON SEARCH_COL
ATTRIBUTES EVENT
WAREHOUSE=CORTEX_WH
TARGET_LAG='1 MINUTE'
AS(
SELECT 
CONCAT('DESCRIPTION: ', DESCRIPTION, '\nNAME: ', NAME) AS SEARCH_COL
,NAME
, DESCRIPTION
,MAIN_SPEAKER
,URL
,EVENT
,TITLE
, SPEAKER_OCCUPATION
,VIEWS
FROM CORTEX_POC.SUMMIT.TED_MAIN
);

select * from transcript limit 5;
--delete from transcript where url='url';

create or replace table TED_WITH_TRANSCRIPT AS
SELECT
tm.URL,
tm.description,
tm.duration,
tm.event,
tm.main_speaker,
tm.name,
tm.title,
ts.transcript
from 
ted_main as tm
inner join transcript ts  on tm.url=ts.url;

select * from ted_with_transcript limit 10;

CREATE OR REPLACE CORTEX SEARCH SERVICE TED_WITH_TRANSCRIPT_SS
ON SEARCH_COL
ATTRIBUTES EVENT
WAREHOUSE=CORTEX_WH
TARGET_LAG='1 MINUTE'
AS(
SELECT 
CONCAT('DESCRIPTION: ', DESCRIPTION, '\nNAME: ', NAME) AS SEARCH_COL
,NAME
, DESCRIPTION
,MAIN_SPEAKER
,URL
,EVENT
,TITLE
,TRANSCRIPT
FROM CORTEX_POC.SUMMIT.TED_WITH_TRANSCRIPT
)