CREATE OR REPLACE DATABASE CORTEX_POC;

CREATE OR REPLACE SCHEMA SUMMIT;

create or replace WAREHOUSE CORTEX_WH WITH WAREHOUSE_SIZE = 'XSMALL' 
WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 600 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 2 SCALING_POLICY = 'STANDARD';

USE ROLE SYSADMIN;
USE DATABASE CORTEX_POC;
USE SCHEMA SUMMIT;
USE WAREHOUSE CORTEX_WH;

--Download data from  Listings.csv from 'https://www.kaggle.com/datasets/mysarahmadbhat/airbnb-listings-reviews/data'

DESCRIBE TABLE CORTEX_POC.SUMMIT.AIRBSNOWFLAKE.CORTEX.SEARCH_PREVIEWNB_LIST;
--DROP TABLE AIRBNB_LIST;

SELECT * FROM CORTEX_POC.SUMMIT.AIRBNB_LIST LIMIT 10;

SELECT DISTINCT amenities FROM AIRBNB_LIST,
        LATERAL FLATTEN(input => AMENITIES) AS AMEN;

CREATE OR REPLACE CORTEX SEARCH SERVICE CORTEX_POC.SUMMIT.AIRBNB_SVC
ON LISTING_TEXT
ATTRIBUTES room_type, amenities
WAREHOUSE = CORTEX_WH
TARGET_LAG = '1 hour'
AS
    SELECT
        NAME,
        CITY,
        PROPERTY_TYPE,
        room_type,
        amenities,
        price,
        REVIEW_SCORES_VALUE,
        (NAME) as listing_text
    FROM
    AIRBNB_LIST;

    