USE ROLE SYSADMIN;

CREATE OR REPLACE DATABASE CORTEX_POC;

CREATE OR REPLACE SCHEMA RAG;

CREATE OR REPLACE WAREHOUSE tasty_bytes_chatbot_wh with
WAREHOUSE_SIZE = LARGE
AUTO_SUSPEND = 60;

CREATE OR REPLACE FILE FORMAT csv_ff 
TYPE = 'csv';

CREATE OR REPLACE STAGE s3load
COMMENT = 'Quickstarts S3 Stage Connection'
url = 's3://sfquickstarts/tastybytes-cx/app/'
file_format = csv_ff;

CREATE OR REPLACE TABLE documents (
	RELATIVE_PATH VARCHAR(16777216),
	RAW_TEXT VARCHAR(16777216)
);

COPY INTO documents
FROM @s3load/documents/;

CREATE OR REPLACE TABLE array_table (
    SOURCE VARCHAR(6),
	SOURCE_DESC VARCHAR(16777216),
	FULL_TEXT VARCHAR(16777216),
	SIZE NUMBER(18,0),
	CHUNK VARCHAR(16777216),
	INPUT_TEXT VARCHAR(16777216),
	CHUNK_EMBEDDING ARRAY
);

COPY INTO array_table
FROM @s3load/vector_store/;

CREATE OR REPLACE TABLE vector_store (
	SOURCE VARCHAR(6),
	SOURCE_DESC VARCHAR(16777216),
	FULL_TEXT VARCHAR(16777216),
	SIZE NUMBER(18,0),
	CHUNK VARCHAR(16777216),
	INPUT_TEXT VARCHAR(16777216),
	CHUNK_EMBEDDING VECTOR(FLOAT, 768)
) AS
SELECT 
  source,
	source_desc,
	full_text,
	size,
	chunk,
	input_text,
  chunk_embedding::VECTOR(FLOAT, 768)
FROM array_table;

SELECT * FROM VECTOR_STORE;
SELECT * FROM DOCUMENTS;